const musicalNotes = {
  CFlat: new Audio("./docs/assets/sounds/musical_notes/B_1.wav"),
  C: new Audio("./docs/assets/sounds/musical_notes/C_1.wav"),
  CSharp: new Audio("./docs/assets/sounds/musical_notes/CSharp_1.wav"),
  DFlat: new Audio("./docs/assets/sounds/musical_notes/CSharp_1.wav"),
  D: new Audio("./docs/assets/sounds/musical_notes/D_1.wav"),
  DSharp: new Audio("./docs/assets/sounds/musical_notes/DSharp_1.wav"),
  EFlat: new Audio("./docs/assets/sounds/musical_notes/DSharp_1.wav"),
  E: new Audio("./docs/assets/sounds/musical_notes/E_1.wav"),
  ESharp: new Audio("./docs/assets/sounds/musical_notes/F_1.wav"),
  FFlat: new Audio("./docs/assets/sounds/musical_notes/E_1.wav"),
  F: new Audio("./docs/assets/sounds/musical_notes/F_1.wav"),
  FSharp: new Audio("./docs/assets/sounds/musical_notes/FSharp_1.wav"),
  GFlat: new Audio("./docs/assets/sounds/musical_notes/FSharp_1.wav"),
  G: new Audio("./docs/assets/sounds/musical_notes/G_1.wav"),
  GSharp: new Audio("./docs/assets/sounds/musical_notes/GSharp_1.wav"),
  AFlat: new Audio("./docs/assets/sounds/musical_notes/GSharp_1.wav"),
  A: new Audio("./docs/assets/sounds/musical_notes/A_1.wav"),
  ASharp: new Audio("./docs/assets/sounds/musical_notes/ASharp_1.wav"),
  BFlat: new Audio("./docs/assets/sounds/musical_notes/ASharp_1.wav"),
  B: new Audio("./docs/assets/sounds/musical_notes/B_1.wav"),
  BSharp: new Audio("./docs/assets/sounds/musical_notes/C_1.wav"),
};

const chordsCMajorScale = {
  CMajor: new Audio("./docs/assets/sounds/chords/CMajor_1.wav"),
  Dminor: new Audio("./docs/assets/sounds/chords/Dminor.wav"),
  Eminor: new Audio("./docs/assets/sounds/chords/Eminor_1.wav"),
  FMajor: new Audio("./docs/assets/sounds/chords/FMajor_1.wav"),
  GMajor: new Audio("./docs/assets/sounds/chords/GMajor_1.wav"),
  Aminor: new Audio("./docs/assets/sounds/chords/Aminor.wav"),
  Bdiminished: new Audio("./docs/assets/sounds/chords/Bdiminished_1.wav"),
};
